apiVersion: 1

prune: true

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: $VICTORIA_METRICS_URL
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.55.0
      timeInterval: 5s
      manageAlerts: false
      disableRecordingRules: true
